### ISSUE TITLE
glob(["**"]) fails on symlink cycles

### ISSUE THREAD

**Issue by kayasoze** [google/bazel#133]
If a directory tree contains a cycle (as with a symlink), bazel will fail.

Example:

$ ls -l sys-root/usr/include/include
sys-root/usr/include/include -> ../include

Build error:
error globbing [**]: [redacted]/sys-root/usr/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include (Too many levels of symbolic links).

**Comment by hanwen** [comment]
i'd suggest to not check in circular symlinks in the buildroot. Many other tools will also choke on this.

**Comment by laszlocsomor** [comment]
Agreed, i'd say this is WAI.
@kayasoze, what do you think should Bazel do?

**Comment by laszlocsomor** [comment]
(WAI = working as intended)

**Comment by kayasoze** [comment]
WAI is just fine by me, actually.  I agree that this case is degenerate and I've worked around it.  I'm really just logging it for posterity.  Thanks!

**Comment by kayasoze** [comment]
It can sometimes be problematic that one can't exclude directories that contain circular symlinks using ```glob(... exclude=["offending_directory"])```.

**Comment by laszlocsomor** [comment]
Yeah that'd be nice to support.

**Comment by hanwen** [comment]
I don't think this is feasible. All patterns (including the exclusions) are executed in parallel for performance reasons. This means we don't have access to the exclusions when evaluate the globs.

**Comment by kchodorow** [comment]
I'm not too familiar with the code, but couldn't we catch the FileSymlinkCycleException at the glob level and swallow it if it was an exclude?

**Comment by hanwen** [comment]
Isn't this an error in 99% of the cases, that we should rather report early?

**Comment by laszlocsomor** [comment]
Yes it is, and that is exactly why kayasoze's request sounds reasonable to me: to be able to exclude such directories.

We have to means so support this. I'm also not (yet) familiar with glob()'s implementation, but if it's not already implemented as a native SkyFunction, it could use RecursiveFilesystemTraversalFunction which is recursive (requests RFTValues for child Dirents) so it can easily stop at excluded directories while not losing any caching.

**Comment by laszlocsomor** [comment]
Oh wait, I was wrong -- the exclusions would have to be part of the SkyKey so the same globs with different exclusions could not share RFTVs. For example, `glob(["a/**/*", exclude=["a/b", "a/d/x"]])` and `glob(["a/**/*", exclude=["a/c", "a/d/y"]])` could not share computation results.

**Comment by janakdr** [comment]
Mark might have some thoughts on this.

**Comment by anakanemison** [comment]
Aha, thanks for the pointer, @janakdr!

@laszlocsomor, there's some support for this sort of thing coming up, for target pattern sequences, when the exclusions are because of negative patterns like "-//foo/bar/..." Perhaps that work could be generalized to the glob case. Unfortunately I'm not yet familiar with their implementation either.

As you note, if SkyKeys contained exclusions they could not directly share computation results. But consider a simpler version of your example:

`key1=glob(["a/**/*", exclude=["a/b"]]),  key2=glob(["a/**/*", exclude=[]])`

The two keys can't directly share results. But if each glob is computed by recursive evaluation, then the part of computing `"a/**/*"` that involves evaluating e.g. `"a/c/**/*"` can be shared between key1 and key2, which gets us most of the way there.
