### ISSUE TITLE
tools/ symlink still required when using a .bazelrc in repository

### ISSUE THREAD

**Issue by ekuefler** [google/bazel#254]
My project checks in a .bazelrc file the repository to provide standard options to all developers. This means that the tweak described in http://bazel.io/blog/2015/04/06/Simplified-Workspace-Creation.html doesn't work, since the system-wide .bazelrc file isn't read if there is a local .bazelrc file, so I still have to symlink tools/ manually.

Maybe Bazel could read non-conflicting options from the home directory .bazelrc instead of ignoring it completely?

**Comment by damienmg** [comment]
Where do you put your bazelrc file?

Master bazelrc's:
  /etc/bazel.bazelrc
  %workspace%/tools/rc.bazel
user bazelrc's:
  --bazelrc=path
  $HOME/.bazelrc
  %workspace%/.bazelrc

It works that way: master bazelrc file are read first except if --nomaster_blazerc option is specified, then the first user bazelrc found is read (meaning that if you specify --bazelrc option then neither $HOME/.bazelrc nor %workspace%/.bazelrc is read).

Note also that if you specify the --package_path in all files, then the user bazelrc's option will replace the master bazelrc ones.

**Comment by ekuefler** [comment]
I have my bazelrc in %workspace%/.bazelrc, right next to the WORKSPACE file. It looks to me like that rc file is taking priority over the one in $HOME/.bazelrc, so the package_path flags in home (which are set up during installation) have no effect.

Is it intended for home to take priority over workspace? That also feels wrong to me.

**Comment by damienmg** [comment]
The code looking for the bazelrc is [there](https://github.com/google/bazel/blob/master/src/main/cpp/option_processor.cc#L273).
So masterc:
 1. depot: tools/bazel.rc
 2. alongside blazerc: path/to/bazel.bazelrc
 3. system-wide: /etc/bazel.bazelrc

Then the [user bazelrc](https://github.com/google/bazel/blob/master/src/main/cpp/option_processor.cc#L202):
 a. command line provided rcfile
 b. workspace rcfile
 c. user's rcfile

The order of reading the files are 1, then 2, then 3 then first one found in a.b.c. The option are then concatenated to the bazel command line so the last package_path is the one used.

That's indeed as you said the workspace file take precedence of the user rcfile. I think that's because we do not check in dotted file in the workspace root so they are user specified and depending on your workspace you might want to have different user specified-one.

For your usage your should use the master bazelrc in tools/bazel.rc. With that, if a user has a ~/.bazelrc, option specified in it will take precedence over those in the workspace rcfile.

**Comment by ekuefler** [comment]
Interesting - so if I understand correctly, you'e suggesting that I not check in %workspace%/.bazelrc, but do check in the same file in %workspace%/tools/bazel.rc. In that case the tools repository in my workspace would have only that one file, which I guess is fine as long as bazel still checks the other tools directory in the package path.  Seems to work okay if I try it out - am I understanding correctly?

**Comment by damienmg** [comment]
Yes. As long as you don't have build file in that directory
Le ven. 19 juin 2015 à 09:23, Erik Kuefler <notifications@github.com> a
écrit :

> Interesting - so if I understand correctly, you'e suggesting that I not
> check in %workspace%/.bazelrc, but do check in the same file in
> %workspace%/tools/bazel.rc. In that case the tools repository in my
> workspace would have only that one file, which I guess is fine as long as
> bazel still checks the other tools directory in the package path. Seems to
> work okay if I try it out - am I understanding correctly?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/bazel/issues/254#issuecomment-113405866>.
>
-- 
Damien

**Comment by ekuefler** [comment]
OK, moving the file to tools/ seems to be working fine for me. Not sure if you want to keep this open or not - still seems a bit surprising that adding a .bazelrc file to the workspace basically breaks the installation, but the workaround is easy and I'm not sure what an alternative solution would be.

**Comment by damienmg** [comment]
It is documented that way. The documentation needs a bit update on that so I will mark it as a documentation issue until the documentation is fixed.

**Comment by damienmg** [comment]
Forgot to mark this bug as fixed:

  - documentation was fixed in bf6dcb7
  - A blog post to clarify in 00e5df7
