### ISSUE TITLE
android ndk build fail

### ISSUE THREAD

**Issue by zagannath** [google/bazel#390]
I followed all given steps for making a shared library in bazel-examples/android-ndk im using mac but its failing

bazel build --dynamic_mode=off --package_path=$HOME/Documents/Code///src/utils:expression_parser_test:/Users/Pankajbafna/Library/Android/ndk/android-ndk:$HOME/bazel --crosstool_top=/Users/Pankajbafna/Library/Android/ndk/android-ndk:toolchain --host_crosstool_top=/Users/Pankajbafna/bazel/tools/cpp:toolchain  --cpu=armeabi-v7a --custom_malloc=/Users/Pankajbafna/Library/Android/ndk/android-ndk:malloc

While parsing option --crosstool_top=/Users/Pankajbafna/Library/Android/ndk/android-ndk:toolchain: invalid label: /Users/Pankajbafna/Library/Android/ndk/android-ndk:toolchain

**Comment by lberki** [comment]
What are you trying to do? In other words, what do you plan to use your shared library for? That file is only of interest if you want to build an Android shared library with Bazel that you will use in some way that Bazel doesn't know about? Even if you want to do that, since then, nicer ways to do it became available.

Here is a simpler list of instructions for building Android apps (the example includes a tiny native library):

https://github.com/google/bazel/tree/master/examples/android

The immediate issue is that `--crosstool_top` and `--crosstool_top` take a label, and `/Users/...:toolchain` is not one. You'd need to put a remote repository (like the `android_ndk_repository` stanza in the WORKSPACE file in the example above) on top of them to make them available for Bazel.

**Comment by zagannath** [comment]
Thanks @lberki issue was with my workspace I fixed it by setting it up properly.
