### ISSUE TITLE
Improve install documentation

### ISSUE THREAD

**Issue by mariusneo** [google/bazel#54]
On the pages :

-  http://bazel.io/docs/getting-started.html
- http://bazel.io/docs/install.html

when building the example projects it is stated that the following commands should be used :
```bash
$ bazel build examples/java:hello-world
```
respectively 
```bash
$ $HOME/bazel/output/bazel build //examples/java-native/src/main/java/com/example/myproject:hello-world
```

but actually the command should look like this : 
```bash
$ bazel build examples/java-native/src/main/java/com/example/myproject:hello-world
```

**Comment by kohlerm** [comment]
Oh and I forgot, at least a few years ago -server was causing the JIT to generate significantly faster code, because it would try harder to optimize the code which causes a longer warm up phase. 
If that is still the case -server might be anyway faster depending on how much needs to be compiled. 
The caveat is of course that one would have to set the memory parameters accordingly.

**Comment by kchodorow** [comment]
I think all of the commands are correct now.  Thank you for the heads-up.
